/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const showConfirmDialog: typeof import('vant/es').showConfirmDialog
  const showDialog: typeof import('vant/es').showDialog
  const showLoadingToast: typeof import('vant/es').showLoadingToast
  const showToast: typeof import('vant/es').showToast
}
